# Two-Stage Hybrid Recommender Experiment

This notebook follows the WideDeep experiment style and evaluates the new
`TwoStageHybridRecommender` on both split protocols:
1. Global temporal split (`train/val/test`)
2. Per-user temporal split (`user_based_temporal_train/val`)

## 1. Imports and Data Loading

In [1]:
!git clone https://$GITHUB_TOKEN@github.com/Its-OP/ucu-rs-2026.git

Cloning into 'ucu-rs-2026'...
remote: Enumerating objects: 625, done.
remote: Counting objects: 100% (104/104), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 625 (delta 87), reused 80 (delta 73), pack-reused 521 (from 1)
Receiving objects: 100% (625/625), 80.22 MiB | 6.24 MiB/s, done.
Resolving deltas: 100% (312/312), done.

In [2]:
%cd ucu-rs-2026

/Users/anastasiiamazur/Projects/ucu-rs-2026/experiments/HybridTwoStage/ucu-rs-2026

In [3]:
import os
import re
import shlex
import subprocess
import sys
import time
from dataclasses import dataclass

import pandas as pd

from src import run_hybrid_two_stage as run_hybrid

## 2. Helpers

In [4]:
@dataclass
class RunResult:
    name: str
    split_type: str
    split: str
    evaluator: str
    command: str
    elapsed_seconds: float
    ndcg_at_10: float | None
    precision_at_10: float | None
    recall_at_10: float | None
    mrr_at_10: float | None
    map_at_10: float | None
    n_users_evaluated: int | None
    skip_rate: float | None
    return_code: int
    success: bool
    error_kind: str | None
    raw_output: str


def _extract_float(pattern: str, text: str):
    m = re.search(pattern, text)
    return float(m.group(1)) if m else None


def _extract_int(pattern: str, text: str):
    m = re.search(pattern, text)
    return int(m.group(1)) if m else None


def parse_metrics(stdout: str):
    ndcg = _extract_float(r"k=10:\s+ndcg=([0-9.]+)", stdout)
    precision = _extract_float(r"k=10:[^\n]*precision=([0-9.]+)", stdout)
    recall = _extract_float(r"k=10:[^\n]*recall=([0-9.]+)", stdout)
    mrr = _extract_float(r"k=10:[^\n]*mrr=([0-9.]+)", stdout)
    map_k10 = _extract_float(r"k=10:[^\n]*map=([0-9.]+)", stdout)

    if ndcg is None:
        ndcg = _extract_float(r"NDCG@10:\s+([0-9.]+)", stdout)
        precision = _extract_float(r"Precision@10:\s+([0-9.]+)", stdout)
        recall = _extract_float(r"Recall@10:\s+([0-9.]+)", stdout)

    n_eval = _extract_int(r"evaluated=([0-9]+)", stdout)
    skip_rate = _extract_float(r"skip rate=([0-9.]+)", stdout)
    return ndcg, precision, recall, mrr, map_k10, n_eval, skip_rate


def _error_kind(return_code: int, output: str) -> str | None:
    if return_code == 0:
        return None
    if return_code == -11:
        return "segmentation_fault"
    if "ModuleNotFoundError" in output:
        return "missing_dependency"
    if "MemoryError" in output:
        return "memory_error"
    return "runtime_error"


def run_hybrid(
    name: str,
    split_type: str,
    split: str,
    evaluator: str,
    extra_args: str = "",
    strict: bool = False,
) -> RunResult:
    cmd = (
        f"{shlex.quote(sys.executable)} -m src.run_hybrid_two_stage "
        f"--split-type {split_type} --split {split} "
        f"--evaluator {evaluator} --ks 10,20 --k 10 "
        f"{extra_args}"
    ).strip()
    print(f"\n=== {name} ===")
    print(cmd)

    safe_env = os.environ.copy()
    safe_env.update({
        "PYTHONFAULTHANDLER": "1",
        "OMP_NUM_THREADS": "1",
        "MKL_NUM_THREADS": "1",
        "OPENBLAS_NUM_THREADS": "1",
        "VECLIB_MAXIMUM_THREADS": "1",
        "NUMEXPR_NUM_THREADS": "1",
    })

    t0 = time.perf_counter()
    proc = subprocess.run(
        cmd,
        shell=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=False,
        env=safe_env,
    )
    elapsed = time.perf_counter() - t0

    out = proc.stdout
    print(out)

    ndcg, precision, recall, mrr, map_k10, n_eval, skip_rate = parse_metrics(out)
    result = RunResult(
        name=name,
        split_type=split_type,
        split=split,
        evaluator=evaluator,
        command=cmd,
        elapsed_seconds=elapsed,
        ndcg_at_10=ndcg,
        precision_at_10=precision,
        recall_at_10=recall,
        mrr_at_10=mrr,
        map_at_10=map_k10,
        n_users_evaluated=n_eval,
        skip_rate=skip_rate,
        return_code=int(proc.returncode),
        success=(proc.returncode == 0),
        error_kind=_error_kind(proc.returncode, out),
        raw_output=out,
    )

    if strict and not result.success:
        raise RuntimeError(f"Command failed with code {proc.returncode}: {cmd}")

    return result

## 3. Global Split Experiments

Tune on `global/val`, then run final report on `global/test` using the best config by NDCG@10.

In [5]:

# Top-5 representative configurations covering the design space explored so far.

# Known test results (global split):
#   blend=1.0  → NDCG@10=0.23863, MRR@10=0.37856
#   blend=0.8  → NDCG@10=0.24517, MRR@10=0.38583
#   blend=0.6  → NDCG@10=0.24762, MRR@10=0.39331  ← current leader
#   blend=0.4  → untested on test set
_COMMON = (
    "--mode all "
    "--content-n-neighbors 5 "
    "--cf-candidates 400 --cb-candidates 120 "
    "--train-cf-candidates 200 --train-cb-candidates 60 "
    "--rerank-holdout-frac 0.10 "
    "--seed 42"
)

global_variants = [
    {
        "name": "hybrid_no_ranker_rrf085",
        "extra_args": f"{_COMMON} --disable-ranker --blend-alpha 0.85",
        "note": "Ablation: CF-dominant RRF, no ML reranker",
    },
    {
        "name": "hybrid_lambdamart_blend1.0",
        "extra_args": f"{_COMMON} --ranker-cf-blend 1.0",
        "note": "Pure LambdaMART output; no BPR score pull",
    },
    {
        "name": "hybrid_lambdamart_blend0.8",
        "extra_args": f"{_COMMON} --ranker-cf-blend 0.8",
        "note": "80% LambdaMART + 20% BPR CF",
    },
    {
        "name": "hybrid_lambdamart_blend0.6",
        "extra_args": f"{_COMMON} --ranker-cf-blend 0.6",
        "note": "60% LambdaMART + 40% BPR CF — best known on test",
    },
    {
        "name": "hybrid_lambdamart_blend0.4",
        "extra_args": f"{_COMMON} --ranker-cf-blend 0.4",
        "note": "40% LambdaMART + 60% BPR CF — extends blend sweep",
    },
]

global_val_runs = []
for cfg in global_variants:
    rr = run_hybrid(
        name=cfg["name"],
        split_type="global",
        split="val",
        evaluator="offline",
        extra_args=cfg["extra_args"],
        strict=False,
    )
    global_val_runs.append(rr)

global_val_df = pd.DataFrame([
    {**r.__dict__, "note": global_variants[i]["note"]}
    for i, r in enumerate(global_val_runs)
])
global_val_df[
    ["name", "note", "success", "ndcg_at_10", "precision_at_10",
     "recall_at_10", "mrr_at_10", "map_at_10",
     "n_users_evaluated", "skip_rate", "elapsed_seconds"]
].sort_values(["success", "ndcg_at_10"], ascending=[False, False])

=== hybrid_no_ranker_rrf085 ===
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/bin/python -m src.run_hybrid_two_stage --split-type global --split val --evaluator offline --ks 10,20 --k 10 --mode all --content-n-neighbors 5 --cf-candidates 400 --cb-candidates 120 --train-cf-candidates 200 --train-cb-candidates 60 --rerank-holdout-frac 0.10 --seed 42 --disable-ranker --blend-alpha 0.85
2026-02-27 22:17:58,513 INFO __main__: Fitting TwoStageHybridRecommender...
2026-02-27 22:17:58,928 INFO src.models.hybrid_two_stage: Fitting BPR component...
2026-02-27 22:18:20,722 INFO src.models.bpr: BPR epoch 1/20, avg loss: 0.441048
2026-02-27 22:18:40,579 INFO src.models.bpr: BPR epoch 2/20, avg loss: 0.356003
2026-02-27 22:19:20,464 INFO src.models.bpr: BPR epoch 4/20, avg loss: 0.333132
2026-02-27 22:19:58,959 INFO src.models.bpr: BPR epoch 6/20, avg loss: 0.326196
2026-02-27 22:20:37,438 INFO src.models.bpr: BPR epoch 8/20, avg loss: 0.318881
2026-02-27 22:21:17,816 INFO src.models.bpr: BPR epoch 10/20, avg loss: 0.311577
2026-02-27 22:21:56,642 INFO src.models.bpr: BPR epoch 12/20, avg loss: 0.302175
2026-02-27 22:22:36,474 INFO src.models.bpr: BPR epoch 14/20, avg loss: 0.292133
2026-02-27 22:23:14,627 INFO src.models.bpr: BPR epoch 16/20, avg loss: 0.279849
2026-02-27 22:23:53,981 INFO src.models.bpr: BPR epoch 18/20, avg loss: 0.269401
2026-02-27 22:24:35,853 INFO src.models.bpr: BPR epoch 20/20, avg loss: 0.261139
2026-02-27 22:24:35,863 INFO src.models.hybrid_two_stage: Fitting content-based component...
2026-02-27 22:25:03,319 WARNING src.eval.offline_ranking: Skipped 4852/6040 users with no relevant items in test set (threshold=4.00)
2026-02-27 22:25:03,345 INFO __main__: === Offline Evaluation ===
2026-02-27 22:25:03,345 INFO __main__: Split type: global
2026-02-27 22:25:03,345 INFO __main__: Split: val
2026-02-27 22:25:03,345 INFO __main__: Mode: all
2026-02-27 22:25:03,345 INFO __main__: Users total=6040, with_gt=1223, eligible=1188, evaluated=1188, skipped=4852
2026-02-27 22:25:03,345 INFO __main__: Coverage rate=1.00000, avg list size=20.00, skip rate=0.80331
2026-02-27 22:25:03,345 INFO __main__: k=10: ndcg=0.29570 precision=0.26396 recall=0.05564 mrr=0.46636 map=0.17936
2026-02-27 22:25:03,345 INFO __main__: k=20: ndcg=0.28525 precision=0.24524 recall=0.08951 mrr=0.47225 map=0.15052


=== hybrid_lambdamart_blend1.0 ===
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/bin/python -m src.run_hybrid_two_stage --split-type global --split val --evaluator offline --ks 10,20 --k 10 --mode all --content-n-neighbors 5 --cf-candidates 400 --cb-candidates 120 --train-cf-candidates 200 --train-cb-candidates 60 --rerank-holdout-frac 0.10 --seed 42 --ranker-cf-blend 1.0
2026-02-27 22:25:11,804 INFO __main__: Reranker holdout generated from training window: base_train=675174 rerank_labels=74977
2026-02-27 22:25:11,804 INFO __main__: Fitting TwoStageHybridRecommender...
2026-02-27 22:25:12,740 INFO src.models.hybrid_two_stage: Fitting BPR component...
2026-02-27 22:25:31,388 INFO src.models.bpr: BPR epoch 1/20, avg loss: 0.445002
2026-02-27 22:25:48,967 INFO src.models.bpr: BPR epoch 2/20, avg loss: 0.356307
2026-02-27 22:26:25,894 INFO src.models.bpr: BPR epoch 4/20, avg loss: 0.331848
2026-02-27 22:27:01,790 INFO src.models.bpr: BPR epoch 6/20, avg loss: 0.323578
2026-02-27 22:27:37,527 INFO src.models.bpr: BPR epoch 8/20, avg loss: 0.317197
2026-02-27 22:28:13,055 INFO src.models.bpr: BPR epoch 10/20, avg loss: 0.310667
2026-02-27 22:28:47,852 INFO src.models.bpr: BPR epoch 12/20, avg loss: 0.302533
2026-02-27 22:29:23,254 INFO src.models.bpr: BPR epoch 14/20, avg loss: 0.293916
2026-02-27 22:29:57,865 INFO src.models.bpr: BPR epoch 16/20, avg loss: 0.284140
2026-02-27 22:30:34,190 INFO src.models.bpr: BPR epoch 18/20, avg loss: 0.274180
2026-02-27 22:31:08,625 INFO src.models.bpr: BPR epoch 20/20, avg loss: 0.264257
2026-02-27 22:31:08,629 INFO src.models.hybrid_two_stage: Fitting content-based component...
2026-02-27 22:31:18,614 INFO src.models.hybrid_two_stage: Training hybrid reranker...
2026-02-27 22:31:41,543 INFO src.models.hybrid_two_stage: Reranker trained: n_users=4609 n_samples=1128499 n_features=16 positive_rate=0.0229
2026-02-27 22:31:41,544 INFO src.models.hybrid_two_stage: Reranker feature importances: {'cf_score_norm': np.int32(602), 'cf_rank_inv': np.int32(675), 'cf_rank_frac': np.int32(271), 'bpr_item_bias': np.int32(905), 'cb_score_norm': np.int32(598), 'cb_rank_inv': np.int32(299), 'cb_rank_frac': np.int32(200), 'in_cf': np.int32(0), 'in_cb': np.int32(0), 'cf_cb_interaction': np.int32(622), 'movie_mean_rating': np.int32(974), 'log_movie_rating_count': np.int32(880), 'user_mean_rating': np.int32(1040), 'user_rating_count': np.int32(960), 'user_liked_count': np.int32(974), 'is_cold_user': np.int32(0)}
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(
2026-02-27 22:32:09,396 WARNING src.eval.offline_ranking: Skipped 4852/6040 users with no relevant items in test set (threshold=4.00)
2026-02-27 22:32:09,426 INFO __main__: === Offline Evaluation ===
2026-02-27 22:32:09,426 INFO __main__: Split type: global
2026-02-27 22:32:09,426 INFO __main__: Split: val
2026-02-27 22:32:09,426 INFO __main__: Mode: all
2026-02-27 22:32:09,426 INFO __main__: Users total=6040, with_gt=1223, eligible=1188, evaluated=1188, skipped=4852
2026-02-27 22:32:09,426 INFO __main__: Coverage rate=1.00000, avg list size=20.00, skip rate=0.80331
2026-02-27 22:32:09,426 INFO __main__: k=10: ndcg=0.19342 precision=0.18288 recall=0.03485 mrr=0.27001 map=0.09764
2026-02-27 22:32:09,426 INFO __main__: k=20: ndcg=0.20903 precision=0.18982 recall=0.06462 mrr=0.28015 map=0.09090


=== hybrid_lambdamart_blend0.8 ===
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/bin/python -m src.run_hybrid_two_stage --split-type global --split val --evaluator offline --ks 10,20 --k 10 --mode all --content-n-neighbors 5 --cf-candidates 400 --cb-candidates 120 --train-cf-candidates 200 --train-cb-candidates 60 --rerank-holdout-frac 0.10 --seed 42 --ranker-cf-blend 0.8
2026-02-27 22:32:18,224 INFO __main__: Reranker holdout generated from training window: base_train=675174 rerank_labels=74977
2026-02-27 22:32:18,225 INFO __main__: Fitting TwoStageHybridRecommender...
2026-02-27 22:32:18,498 INFO src.models.hybrid_two_stage: Fitting BPR component...
2026-02-27 22:32:36,425 INFO src.models.bpr: BPR epoch 1/20, avg loss: 0.445002
2026-02-27 22:32:53,655 INFO src.models.bpr: BPR epoch 2/20, avg loss: 0.356307
2026-02-27 22:33:29,521 INFO src.models.bpr: BPR epoch 4/20, avg loss: 0.331848
2026-02-27 22:34:04,208 INFO src.models.bpr: BPR epoch 6/20, avg loss: 0.323578
2026-02-27 22:34:39,629 INFO src.models.bpr: BPR epoch 8/20, avg loss: 0.317197
2026-02-27 22:35:14,772 INFO src.models.bpr: BPR epoch 10/20, avg loss: 0.310667
2026-02-27 22:35:49,435 INFO src.models.bpr: BPR epoch 12/20, avg loss: 0.302533
2026-02-27 22:36:24,696 INFO src.models.bpr: BPR epoch 14/20, avg loss: 0.293916
2026-02-27 22:37:00,168 INFO src.models.bpr: BPR epoch 16/20, avg loss: 0.284140
2026-02-27 22:37:35,942 INFO src.models.bpr: BPR epoch 18/20, avg loss: 0.274180
2026-02-27 22:38:10,514 INFO src.models.bpr: BPR epoch 20/20, avg loss: 0.264257
2026-02-27 22:38:10,518 INFO src.models.hybrid_two_stage: Fitting content-based component...
2026-02-27 22:38:21,108 INFO src.models.hybrid_two_stage: Training hybrid reranker...
2026-02-27 22:38:40,901 INFO src.models.hybrid_two_stage: Reranker trained: n_users=4603 n_samples=1127067 n_features=16 positive_rate=0.0229
2026-02-27 22:38:40,901 INFO src.models.hybrid_two_stage: Reranker feature importances: {'cf_score_norm': np.int32(619), 'cf_rank_inv': np.int32(688), 'cf_rank_frac': np.int32(241), 'bpr_item_bias': np.int32(924), 'cb_score_norm': np.int32(607), 'cb_rank_inv': np.int32(284), 'cb_rank_frac': np.int32(238), 'in_cf': np.int32(0), 'in_cb': np.int32(0), 'cf_cb_interaction': np.int32(517), 'movie_mean_rating': np.int32(1023), 'log_movie_rating_count': np.int32(915), 'user_mean_rating': np.int32(1047), 'user_rating_count': np.int32(931), 'user_liked_count': np.int32(965), 'is_cold_user': np.int32(1)}
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(
2026-02-27 22:39:08,035 WARNING src.eval.offline_ranking: Skipped 4852/6040 users with no relevant items in test set (threshold=4.00)
2026-02-27 22:39:08,063 INFO __main__: === Offline Evaluation ===
2026-02-27 22:39:08,063 INFO __main__: Split type: global
2026-02-27 22:39:08,063 INFO __main__: Split: val
2026-02-27 22:39:08,063 INFO __main__: Mode: all
2026-02-27 22:39:08,063 INFO __main__: Users total=6040, with_gt=1223, eligible=1188, evaluated=1188, skipped=4852
2026-02-27 22:39:08,063 INFO __main__: Coverage rate=1.00000, avg list size=20.00, skip rate=0.80331
2026-02-27 22:39:08,063 INFO __main__: k=10: ndcg=0.24923 precision=0.22576 recall=0.04741 mrr=0.38380 map=0.13520
2026-02-27 22:39:08,063 INFO __main__: k=20: ndcg=0.25102 precision=0.22142 recall=0.07999 mrr=0.39051 map=0.11929


=== hybrid_lambdamart_blend0.6 ===
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/bin/python -m src.run_hybrid_two_stage --split-type global --split val --evaluator offline --ks 10,20 --k 10 --mode all --content-n-neighbors 5 --cf-candidates 400 --cb-candidates 120 --train-cf-candidates 200 --train-cb-candidates 60 --rerank-holdout-frac 0.10 --seed 42 --ranker-cf-blend 0.6
2026-02-27 22:39:16,671 INFO __main__: Reranker holdout generated from training window: base_train=675174 rerank_labels=74977
2026-02-27 22:39:16,672 INFO __main__: Fitting TwoStageHybridRecommender...
2026-02-27 22:39:16,935 INFO src.models.hybrid_two_stage: Fitting BPR component...
2026-02-27 22:39:34,672 INFO src.models.bpr: BPR epoch 1/20, avg loss: 0.445002
2026-02-27 22:39:51,878 INFO src.models.bpr: BPR epoch 2/20, avg loss: 0.356307
2026-02-27 22:40:27,135 INFO src.models.bpr: BPR epoch 4/20, avg loss: 0.331848
2026-02-27 22:41:01,805 INFO src.models.bpr: BPR epoch 6/20, avg loss: 0.323578
2026-02-27 22:41:37,512 INFO src.models.bpr: BPR epoch 8/20, avg loss: 0.317197
2026-02-27 22:42:11,857 INFO src.models.bpr: BPR epoch 10/20, avg loss: 0.310667
2026-02-27 22:42:47,612 INFO src.models.bpr: BPR epoch 12/20, avg loss: 0.302533
2026-02-27 22:43:23,099 INFO src.models.bpr: BPR epoch 14/20, avg loss: 0.293916
2026-02-27 22:43:57,799 INFO src.models.bpr: BPR epoch 16/20, avg loss: 0.284140
2026-02-27 22:44:32,880 INFO src.models.bpr: BPR epoch 18/20, avg loss: 0.274180
2026-02-27 22:45:06,460 INFO src.models.bpr: BPR epoch 20/20, avg loss: 0.264257
2026-02-27 22:45:06,464 INFO src.models.hybrid_two_stage: Fitting content-based component...
2026-02-27 22:45:16,824 INFO src.models.hybrid_two_stage: Training hybrid reranker...
2026-02-27 22:45:36,095 INFO src.models.hybrid_two_stage: Reranker trained: n_users=4610 n_samples=1128751 n_features=16 positive_rate=0.0229
2026-02-27 22:45:36,095 INFO src.models.hybrid_two_stage: Reranker feature importances: {'cf_score_norm': np.int32(634), 'cf_rank_inv': np.int32(652), 'cf_rank_frac': np.int32(229), 'bpr_item_bias': np.int32(925), 'cb_score_norm': np.int32(567), 'cb_rank_inv': np.int32(294), 'cb_rank_frac': np.int32(207), 'in_cf': np.int32(0), 'in_cb': np.int32(0), 'cf_cb_interaction': np.int32(478), 'movie_mean_rating': np.int32(1011), 'log_movie_rating_count': np.int32(930), 'user_mean_rating': np.int32(1103), 'user_rating_count': np.int32(1015), 'user_liked_count': np.int32(953), 'is_cold_user': np.int32(2)}
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(
2026-02-27 22:46:03,008 WARNING src.eval.offline_ranking: Skipped 4852/6040 users with no relevant items in test set (threshold=4.00)
2026-02-27 22:46:03,035 INFO __main__: === Offline Evaluation ===
2026-02-27 22:46:03,035 INFO __main__: Split type: global
2026-02-27 22:46:03,036 INFO __main__: Split: val
2026-02-27 22:46:03,036 INFO __main__: Mode: all
2026-02-27 22:46:03,036 INFO __main__: Users total=6040, with_gt=1223, eligible=1188, evaluated=1188, skipped=4852
2026-02-27 22:46:03,037 INFO __main__: Coverage rate=1.00000, avg list size=20.00, skip rate=0.80331
2026-02-27 22:46:03,037 INFO __main__: k=10: ndcg=0.26607 precision=0.24485 recall=0.05148 mrr=0.39314 map=0.15521
2026-02-27 22:46:03,037 INFO __main__: k=20: ndcg=0.26260 precision=0.23069 recall=0.08400 mrr=0.39847 map=0.13282


=== hybrid_lambdamart_blend0.4 ===
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/bin/python -m src.run_hybrid_two_stage --split-type global --split val --evaluator offline --ks 10,20 --k 10 --mode all --content-n-neighbors 5 --cf-candidates 400 --cb-candidates 120 --train-cf-candidates 200 --train-cb-candidates 60 --rerank-holdout-frac 0.10 --seed 42 --ranker-cf-blend 0.4
2026-02-27 22:46:10,355 INFO __main__: Reranker holdout generated from training window: base_train=675174 rerank_labels=74977
2026-02-27 22:46:10,355 INFO __main__: Fitting TwoStageHybridRecommender...
2026-02-27 22:46:10,613 INFO src.models.hybrid_two_stage: Fitting BPR component...
2026-02-27 22:46:30,241 INFO src.models.bpr: BPR epoch 1/20, avg loss: 0.445002
2026-02-27 22:46:48,026 INFO src.models.bpr: BPR epoch 2/20, avg loss: 0.356307
2026-02-27 22:47:24,101 INFO src.models.bpr: BPR epoch 4/20, avg loss: 0.331848
2026-02-27 22:47:59,603 INFO src.models.bpr: BPR epoch 6/20, avg loss: 0.323578
2026-02-27 22:48:35,082 INFO src.models.bpr: BPR epoch 8/20, avg loss: 0.317197
2026-02-27 22:49:09,772 INFO src.models.bpr: BPR epoch 10/20, avg loss: 0.310667
2026-02-27 22:49:45,498 INFO src.models.bpr: BPR epoch 12/20, avg loss: 0.302533
2026-02-27 22:50:20,850 INFO src.models.bpr: BPR epoch 14/20, avg loss: 0.293916
2026-02-27 22:50:57,352 INFO src.models.bpr: BPR epoch 16/20, avg loss: 0.284140
2026-02-27 22:51:34,464 INFO src.models.bpr: BPR epoch 18/20, avg loss: 0.274180
2026-02-27 22:52:09,379 INFO src.models.bpr: BPR epoch 20/20, avg loss: 0.264257
2026-02-27 22:52:09,382 INFO src.models.hybrid_two_stage: Fitting content-based component...
2026-02-27 22:52:19,860 INFO src.models.hybrid_two_stage: Training hybrid reranker...
2026-02-27 22:52:39,360 INFO src.models.hybrid_two_stage: Reranker trained: n_users=4608 n_samples=1128217 n_features=16 positive_rate=0.0229
2026-02-27 22:52:39,361 INFO src.models.hybrid_two_stage: Reranker feature importances: {'cf_score_norm': np.int32(585), 'cf_rank_inv': np.int32(650), 'cf_rank_frac': np.int32(203), 'bpr_item_bias': np.int32(895), 'cb_score_norm': np.int32(656), 'cb_rank_inv': np.int32(322), 'cb_rank_frac': np.int32(243), 'in_cf': np.int32(0), 'in_cb': np.int32(0), 'cf_cb_interaction': np.int32(560), 'movie_mean_rating': np.int32(1058), 'log_movie_rating_count': np.int32(899), 'user_mean_rating': np.int32(969), 'user_rating_count': np.int32(963), 'user_liked_count': np.int32(996), 'is_cold_user': np.int32(1)}
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(
2026-02-27 22:53:06,577 WARNING src.eval.offline_ranking: Skipped 4852/6040 users with no relevant items in test set (threshold=4.00)
2026-02-27 22:53:06,605 INFO __main__: === Offline Evaluation ===
2026-02-27 22:53:06,605 INFO __main__: Split type: global
2026-02-27 22:53:06,606 INFO __main__: Split: val
2026-02-27 22:53:06,606 INFO __main__: Mode: all
2026-02-27 22:53:06,606 INFO __main__: Users total=6040, with_gt=1223, eligible=1188, evaluated=1188, skipped=4852
2026-02-27 22:53:06,606 INFO __main__: Coverage rate=1.00000, avg list size=20.00, skip rate=0.80331
2026-02-27 22:53:06,606 INFO __main__: k=10: ndcg=0.28204 precision=0.25274 recall=0.05213 mrr=0.44569 map=0.16399
2026-02-27 22:53:06,606 INFO __main__: k=20: ndcg=0.27568 precision=0.23659 recall=0.08495 mrr=0.45173 map=0.13990

,name,note,success,ndcg_at_10,precision_at_10,recall_at_10,mrr_at_10,map_at_10,n_users_evaluated,skip_rate,elapsed_seconds
0,hybrid_no_ranker_rrf085,"Ablation: CF-dominant RRF, no ML reranker",True,0.29570,0.26396,0.05564,0.46636,0.17936,1188,0.80331,432.624485
4,hybrid_lambdamart_blend0.4,40% LambdaMART + 60% BPR CF — extends blend sweep,True,0.28204,0.25274,0.05213,0.44569,0.16399,1188,0.80331,423.551205
3,hybrid_lambdamart_blend0.6,60% LambdaMART + 40% BPR CF — best known on test,True,0.26607,0.24485,0.05148,0.39314,0.15521,1188,0.80331,414.968163
2,hybrid_lambdamart_blend0.8,80% LambdaMART + 20% BPR CF,True,0.24923,0.22576,0.04741,0.38380,0.13520,1188,0.80331,418.608836
1,hybrid_lambdamart_blend1.0,Pure LambdaMART output; no BPR score pull,True,0.19342,0.18288,0.03485,0.27001,0.09764,1188,0.80331,425.889621

In [6]:

# pick the best config by NDCG@10 on val, then run it on test.
global_ok_df = global_val_df[
    (global_val_df["success"]) & (global_val_df["ndcg_at_10"].notna())
]
best_global = global_ok_df.sort_values("ndcg_at_10", ascending=False).iloc[0]
print(f"Best val variant: {best_global['name']}  (NDCG@10={best_global['ndcg_at_10']:.5f})")

best_cfg = next(cfg for cfg in global_variants if cfg["name"] == best_global["name"])
best_global_test = run_hybrid(
    name=f"{best_global['name']}_test",
    split_type="global",
    split="test",
    evaluator="offline",
    extra_args=best_cfg["extra_args"],
    strict=False,
)

pd.DataFrame([{**best_global_test.__dict__, "note": best_cfg["note"]}])[
    ["name", "note", "success", "return_code", "split_type", "split",
     "ndcg_at_10", "precision_at_10", "recall_at_10", "mrr_at_10",
     "map_at_10", "n_users_evaluated", "skip_rate", "elapsed_seconds"]
]

Best val variant: hybrid_no_ranker_rrf085  (NDCG@10=0.29570)

=== hybrid_no_ranker_rrf085_test ===
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/bin/python -m src.run_hybrid_two_stage --split-type global --split test --evaluator offline --ks 10,20 --k 10 --mode all --content-n-neighbors 5 --cf-candidates 400 --cb-candidates 120 --train-cf-candidates 200 --train-cb-candidates 60 --rerank-holdout-frac 0.10 --seed 42 --disable-ranker --blend-alpha 0.85
2026-02-27 22:53:14,357 INFO __main__: Fitting TwoStageHybridRecommender...
2026-02-27 22:53:14,773 INFO src.models.hybrid_two_stage: Fitting BPR component...
2026-02-27 22:53:34,475 INFO src.models.bpr: BPR epoch 1/20, avg loss: 0.441048
2026-02-27 22:53:53,574 INFO src.models.bpr: BPR epoch 2/20, avg loss: 0.356003
2026-02-27 22:54:32,521 INFO src.models.bpr: BPR epoch 4/20, avg loss: 0.333132
2026-02-27 22:55:11,359 INFO src.models.bpr: BPR epoch 6/20, avg loss: 0.326196
2026-02-27 22:55:51,451 INFO src.models.bpr: BPR epoch 8/20, avg loss: 0.318881
2026-02-27 22:56:31,036 INFO src.models.bpr: BPR epoch 10/20, avg loss: 0.311577
2026-02-27 22:57:09,611 INFO src.models.bpr: BPR epoch 12/20, avg loss: 0.302175
2026-02-27 22:57:48,446 INFO src.models.bpr: BPR epoch 14/20, avg loss: 0.292133
2026-02-27 22:58:27,637 INFO src.models.bpr: BPR epoch 16/20, avg loss: 0.279849
2026-02-27 22:59:06,271 INFO src.models.bpr: BPR epoch 18/20, avg loss: 0.269401
2026-02-27 22:59:45,827 INFO src.models.bpr: BPR epoch 20/20, avg loss: 0.261139
2026-02-27 22:59:45,829 INFO src.models.hybrid_two_stage: Fitting content-based component...
2026-02-27 23:00:11,490 WARNING src.eval.offline_ranking: Skipped 4693/6040 users with no relevant items in test set (threshold=4.00)
2026-02-27 23:00:11,514 INFO __main__: === Offline Evaluation ===
2026-02-27 23:00:11,514 INFO __main__: Split type: global
2026-02-27 23:00:11,515 INFO __main__: Split: test
2026-02-27 23:00:11,515 INFO __main__: Mode: all
2026-02-27 23:00:11,515 INFO __main__: Users total=6040, with_gt=1367, eligible=1347, evaluated=1347, skipped=4693
2026-02-27 23:00:11,515 INFO __main__: Coverage rate=1.00000, avg list size=20.00, skip rate=0.77699
2026-02-27 23:00:11,515 INFO __main__: k=10: ndcg=0.23709 precision=0.21007 recall=0.04958 mrr=0.37669 map=0.13406
2026-02-27 23:00:11,515 INFO __main__: k=20: ndcg=0.23025 precision=0.19236 recall=0.07574 mrr=0.38395 map=0.11100

,name,note,success,return_code,split_type,split,ndcg_at_10,precision_at_10,recall_at_10,mrr_at_10,map_at_10,n_users_evaluated,skip_rate,elapsed_seconds
0,hybrid_no_ranker_rrf085_test,"Ablation: CF-dominant RRF, no ML reranker",True,0,global,test,0.23709,0.21007,0.04958,0.37669,0.13406,1347,0.77699,425.246775

## 4. Per-User Split Experiments

Run the same variant family on `per_user/val`.

In [7]:

# run all 5 configs on per-user temporal split
per_user_runs = []
for cfg in global_variants:
    rr = run_hybrid(
        name=cfg["name"],
        split_type="per_user",
        split="val",
        evaluator="offline",
        extra_args=cfg["extra_args"],
        strict=False,
    )
    per_user_runs.append(rr)

per_user_df = pd.DataFrame([
    {**r.__dict__, "note": global_variants[i]["note"]}
    for i, r in enumerate(per_user_runs)
])
per_user_df[
    ["name", "note", "success", "ndcg_at_10", "precision_at_10",
     "recall_at_10", "mrr_at_10", "map_at_10",
     "n_users_evaluated", "skip_rate", "elapsed_seconds"]
].sort_values(["success", "ndcg_at_10"], ascending=[False, False])

=== hybrid_no_ranker_rrf085 ===
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/bin/python -m src.run_hybrid_two_stage --split-type per_user --split val --evaluator offline --ks 10,20 --k 10 --mode all --content-n-neighbors 5 --cf-candidates 400 --cb-candidates 120 --train-cf-candidates 200 --train-cb-candidates 60 --rerank-holdout-frac 0.10 --seed 42 --disable-ranker --blend-alpha 0.85
2026-02-27 23:00:19,006 INFO __main__: Fitting TwoStageHybridRecommender...
2026-02-27 23:00:19,310 INFO src.models.hybrid_two_stage: Fitting BPR component...
2026-02-27 23:00:39,344 INFO src.models.bpr: BPR epoch 1/20, avg loss: 0.434580
2026-02-27 23:00:58,902 INFO src.models.bpr: BPR epoch 2/20, avg loss: 0.350822
2026-02-27 23:01:38,591 INFO src.models.bpr: BPR epoch 4/20, avg loss: 0.328740
2026-02-27 23:02:18,597 INFO src.models.bpr: BPR epoch 6/20, avg loss: 0.321364
2026-02-27 23:02:56,547 INFO src.models.bpr: BPR epoch 8/20, avg loss: 0.314320
2026-02-27 23:03:34,982 INFO src.models.bpr: BPR epoch 10/20, avg loss: 0.308057
2026-02-27 23:04:13,780 INFO src.models.bpr: BPR epoch 12/20, avg loss: 0.300080
2026-02-27 23:04:51,773 INFO src.models.bpr: BPR epoch 14/20, avg loss: 0.291103
2026-02-27 23:05:30,939 INFO src.models.bpr: BPR epoch 16/20, avg loss: 0.281520
2026-02-27 23:06:10,009 INFO src.models.bpr: BPR epoch 18/20, avg loss: 0.270769
2026-02-27 23:06:49,343 INFO src.models.bpr: BPR epoch 20/20, avg loss: 0.263087
2026-02-27 23:06:49,346 INFO src.models.hybrid_two_stage: Fitting content-based component...
2026-02-27 23:07:16,572 WARNING src.eval.offline_ranking: Skipped 41/6040 users with no relevant items in test set (threshold=4.00)
2026-02-27 23:07:16,605 INFO __main__: === Offline Evaluation ===
2026-02-27 23:07:16,605 INFO __main__: Split type: per_user
2026-02-27 23:07:16,605 INFO __main__: Split: val
2026-02-27 23:07:16,605 INFO __main__: Mode: all
2026-02-27 23:07:16,605 INFO __main__: Users total=6040, with_gt=6040, eligible=5999, evaluated=5999, skipped=41
2026-02-27 23:07:16,605 INFO __main__: Coverage rate=1.00000, avg list size=20.00, skip rate=0.00679
2026-02-27 23:07:16,605 INFO __main__: k=10: ndcg=0.14293 precision=0.12292 recall=0.05751 mrr=0.26528 map=0.06885
2026-02-27 23:07:16,605 INFO __main__: k=20: ndcg=0.14597 precision=0.11197 recall=0.07671 mrr=0.27479 map=0.05826


=== hybrid_lambdamart_blend1.0 ===
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/bin/python -m src.run_hybrid_two_stage --split-type per_user --split val --evaluator offline --ks 10,20 --k 10 --mode all --content-n-neighbors 5 --cf-candidates 400 --cb-candidates 120 --train-cf-candidates 200 --train-cb-candidates 60 --rerank-holdout-frac 0.10 --seed 42 --ranker-cf-blend 1.0
2026-02-27 23:07:24,272 INFO __main__: Reranker holdout generated from training window: base_train=672936 rerank_labels=74973
2026-02-27 23:07:24,272 INFO __main__: Fitting TwoStageHybridRecommender...
2026-02-27 23:07:24,563 INFO src.models.hybrid_two_stage: Fitting BPR component...
2026-02-27 23:07:42,150 INFO src.models.bpr: BPR epoch 1/20, avg loss: 0.438777
2026-02-27 23:07:59,022 INFO src.models.bpr: BPR epoch 2/20, avg loss: 0.351692
2026-02-27 23:08:33,982 INFO src.models.bpr: BPR epoch 4/20, avg loss: 0.328003
2026-02-27 23:09:08,109 INFO src.models.bpr: BPR epoch 6/20, avg loss: 0.320536
2026-02-27 23:09:42,905 INFO src.models.bpr: BPR epoch 8/20, avg loss: 0.313990
2026-02-27 23:10:17,767 INFO src.models.bpr: BPR epoch 10/20, avg loss: 0.307143
2026-02-27 23:10:51,947 INFO src.models.bpr: BPR epoch 12/20, avg loss: 0.300973
2026-02-27 23:11:26,600 INFO src.models.bpr: BPR epoch 14/20, avg loss: 0.294364
2026-02-27 23:12:00,373 INFO src.models.bpr: BPR epoch 16/20, avg loss: 0.285633
2026-02-27 23:12:34,808 INFO src.models.bpr: BPR epoch 18/20, avg loss: 0.276491
2026-02-27 23:13:08,619 INFO src.models.bpr: BPR epoch 20/20, avg loss: 0.267014
2026-02-27 23:13:08,620 INFO src.models.hybrid_two_stage: Fitting content-based component...
2026-02-27 23:13:19,188 INFO src.models.hybrid_two_stage: Training hybrid reranker...
2026-02-27 23:13:39,316 INFO src.models.hybrid_two_stage: Reranker trained: n_users=5437 n_samples=1328047 n_features=16 positive_rate=0.0209
2026-02-27 23:13:39,316 INFO src.models.hybrid_two_stage: Reranker feature importances: {'cf_score_norm': np.int32(712), 'cf_rank_inv': np.int32(743), 'cf_rank_frac': np.int32(272), 'bpr_item_bias': np.int32(987), 'cb_score_norm': np.int32(648), 'cb_rank_inv': np.int32(349), 'cb_rank_frac': np.int32(181), 'in_cf': np.int32(0), 'in_cb': np.int32(0), 'cf_cb_interaction': np.int32(540), 'movie_mean_rating': np.int32(982), 'log_movie_rating_count': np.int32(770), 'user_mean_rating': np.int32(984), 'user_rating_count': np.int32(1005), 'user_liked_count': np.int32(827), 'is_cold_user': np.int32(0)}
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(
2026-02-27 23:14:07,194 WARNING src.eval.offline_ranking: Skipped 41/6040 users with no relevant items in test set (threshold=4.00)
2026-02-27 23:14:07,226 INFO __main__: === Offline Evaluation ===
2026-02-27 23:14:07,226 INFO __main__: Split type: per_user
2026-02-27 23:14:07,227 INFO __main__: Split: val
2026-02-27 23:14:07,227 INFO __main__: Mode: all
2026-02-27 23:14:07,227 INFO __main__: Users total=6040, with_gt=6040, eligible=5999, evaluated=5999, skipped=41
2026-02-27 23:14:07,227 INFO __main__: Coverage rate=1.00000, avg list size=20.00, skip rate=0.00679
2026-02-27 23:14:07,227 INFO __main__: k=10: ndcg=0.10534 precision=0.08841 recall=0.04392 mrr=0.18787 map=0.03934
2026-02-27 23:14:07,227 INFO __main__: k=20: ndcg=0.11581 precision=0.08482 recall=0.05988 mrr=0.19910 map=0.03605


=== hybrid_lambdamart_blend0.8 ===
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/bin/python -m src.run_hybrid_two_stage --split-type per_user --split val --evaluator offline --ks 10,20 --k 10 --mode all --content-n-neighbors 5 --cf-candidates 400 --cb-candidates 120 --train-cf-candidates 200 --train-cb-candidates 60 --rerank-holdout-frac 0.10 --seed 42 --ranker-cf-blend 0.8
2026-02-27 23:14:15,251 INFO __main__: Reranker holdout generated from training window: base_train=672936 rerank_labels=74973
2026-02-27 23:14:15,251 INFO __main__: Fitting TwoStageHybridRecommender...
2026-02-27 23:14:15,540 INFO src.models.hybrid_two_stage: Fitting BPR component...
2026-02-27 23:14:33,181 INFO src.models.bpr: BPR epoch 1/20, avg loss: 0.438777
2026-02-27 23:14:50,187 INFO src.models.bpr: BPR epoch 2/20, avg loss: 0.351692
2026-02-27 23:15:24,873 INFO src.models.bpr: BPR epoch 4/20, avg loss: 0.328003
2026-02-27 23:15:59,399 INFO src.models.bpr: BPR epoch 6/20, avg loss: 0.320536
2026-02-27 23:16:35,948 INFO src.models.bpr: BPR epoch 8/20, avg loss: 0.313990
2026-02-27 23:17:10,301 INFO src.models.bpr: BPR epoch 10/20, avg loss: 0.307143
2026-02-27 23:17:45,643 INFO src.models.bpr: BPR epoch 12/20, avg loss: 0.300973
2026-02-27 23:18:20,785 INFO src.models.bpr: BPR epoch 14/20, avg loss: 0.294364
2026-02-27 23:18:54,676 INFO src.models.bpr: BPR epoch 16/20, avg loss: 0.285633
2026-02-27 23:19:29,390 INFO src.models.bpr: BPR epoch 18/20, avg loss: 0.276491
2026-02-27 23:20:03,333 INFO src.models.bpr: BPR epoch 20/20, avg loss: 0.267014
2026-02-27 23:20:03,342 INFO src.models.hybrid_two_stage: Fitting content-based component...
2026-02-27 23:20:14,139 INFO src.models.hybrid_two_stage: Training hybrid reranker...
2026-02-27 23:20:35,846 INFO src.models.hybrid_two_stage: Reranker trained: n_users=5433 n_samples=1327066 n_features=16 positive_rate=0.0209
2026-02-27 23:20:35,846 INFO src.models.hybrid_two_stage: Reranker feature importances: {'cf_score_norm': np.int32(646), 'cf_rank_inv': np.int32(730), 'cf_rank_frac': np.int32(256), 'bpr_item_bias': np.int32(996), 'cb_score_norm': np.int32(552), 'cb_rank_inv': np.int32(364), 'cb_rank_frac': np.int32(179), 'in_cf': np.int32(0), 'in_cb': np.int32(2), 'cf_cb_interaction': np.int32(580), 'movie_mean_rating': np.int32(973), 'log_movie_rating_count': np.int32(804), 'user_mean_rating': np.int32(1096), 'user_rating_count': np.int32(998), 'user_liked_count': np.int32(824), 'is_cold_user': np.int32(0)}
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(
2026-02-27 23:21:03,931 WARNING src.eval.offline_ranking: Skipped 41/6040 users with no relevant items in test set (threshold=4.00)
2026-02-27 23:21:03,963 INFO __main__: === Offline Evaluation ===
2026-02-27 23:21:03,963 INFO __main__: Split type: per_user
2026-02-27 23:21:03,963 INFO __main__: Split: val
2026-02-27 23:21:03,963 INFO __main__: Mode: all
2026-02-27 23:21:03,963 INFO __main__: Users total=6040, with_gt=6040, eligible=5999, evaluated=5999, skipped=41
2026-02-27 23:21:03,963 INFO __main__: Coverage rate=1.00000, avg list size=20.00, skip rate=0.00679
2026-02-27 23:21:03,963 INFO __main__: k=10: ndcg=0.11981 precision=0.10291 recall=0.04894 mrr=0.21283 map=0.04905
2026-02-27 23:21:03,963 INFO __main__: k=20: ndcg=0.12814 precision=0.09684 recall=0.06702 mrr=0.22316 map=0.04350


=== hybrid_lambdamart_blend0.6 ===
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/bin/python -m src.run_hybrid_two_stage --split-type per_user --split val --evaluator offline --ks 10,20 --k 10 --mode all --content-n-neighbors 5 --cf-candidates 400 --cb-candidates 120 --train-cf-candidates 200 --train-cb-candidates 60 --rerank-holdout-frac 0.10 --seed 42 --ranker-cf-blend 0.6
2026-02-27 23:21:11,763 INFO __main__: Reranker holdout generated from training window: base_train=672936 rerank_labels=74973
2026-02-27 23:21:11,763 INFO __main__: Fitting TwoStageHybridRecommender...
2026-02-27 23:21:12,838 INFO src.models.hybrid_two_stage: Fitting BPR component...
2026-02-27 23:21:31,094 INFO src.models.bpr: BPR epoch 1/20, avg loss: 0.438777
2026-02-27 23:21:48,290 INFO src.models.bpr: BPR epoch 2/20, avg loss: 0.351692
2026-02-27 23:22:23,146 INFO src.models.bpr: BPR epoch 4/20, avg loss: 0.328003
2026-02-27 23:22:58,208 INFO src.models.bpr: BPR epoch 6/20, avg loss: 0.320536
2026-02-27 23:23:33,167 INFO src.models.bpr: BPR epoch 8/20, avg loss: 0.313990
2026-02-27 23:24:07,139 INFO src.models.bpr: BPR epoch 10/20, avg loss: 0.307143
2026-02-27 23:24:41,945 INFO src.models.bpr: BPR epoch 12/20, avg loss: 0.300973
2026-02-27 23:25:17,137 INFO src.models.bpr: BPR epoch 14/20, avg loss: 0.294364
2026-02-27 23:25:51,719 INFO src.models.bpr: BPR epoch 16/20, avg loss: 0.285633
2026-02-27 23:26:26,544 INFO src.models.bpr: BPR epoch 18/20, avg loss: 0.276491
2026-02-27 23:27:00,607 INFO src.models.bpr: BPR epoch 20/20, avg loss: 0.267014
2026-02-27 23:27:00,611 INFO src.models.hybrid_two_stage: Fitting content-based component...
2026-02-27 23:27:10,410 INFO src.models.hybrid_two_stage: Training hybrid reranker...
2026-02-27 23:27:31,508 INFO src.models.hybrid_two_stage: Reranker trained: n_users=5431 n_samples=1326403 n_features=16 positive_rate=0.0209
2026-02-27 23:27:31,508 INFO src.models.hybrid_two_stage: Reranker feature importances: {'cf_score_norm': np.int32(669), 'cf_rank_inv': np.int32(740), 'cf_rank_frac': np.int32(277), 'bpr_item_bias': np.int32(945), 'cb_score_norm': np.int32(621), 'cb_rank_inv': np.int32(347), 'cb_rank_frac': np.int32(160), 'in_cf': np.int32(1), 'in_cb': np.int32(0), 'cf_cb_interaction': np.int32(556), 'movie_mean_rating': np.int32(1001), 'log_movie_rating_count': np.int32(766), 'user_mean_rating': np.int32(1034), 'user_rating_count': np.int32(1025), 'user_liked_count': np.int32(858), 'is_cold_user': np.int32(0)}
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(
2026-02-27 23:27:58,617 WARNING src.eval.offline_ranking: Skipped 41/6040 users with no relevant items in test set (threshold=4.00)
2026-02-27 23:27:58,648 INFO __main__: === Offline Evaluation ===
2026-02-27 23:27:58,648 INFO __main__: Split type: per_user
2026-02-27 23:27:58,648 INFO __main__: Split: val
2026-02-27 23:27:58,648 INFO __main__: Mode: all
2026-02-27 23:27:58,648 INFO __main__: Users total=6040, with_gt=6040, eligible=5999, evaluated=5999, skipped=41
2026-02-27 23:27:58,648 INFO __main__: Coverage rate=1.00000, avg list size=20.00, skip rate=0.00679
2026-02-27 23:27:58,648 INFO __main__: k=10: ndcg=0.12510 precision=0.10774 recall=0.05010 mrr=0.23049 map=0.05490
2026-02-27 23:27:58,648 INFO __main__: k=20: ndcg=0.13023 precision=0.09920 recall=0.06814 mrr=0.24058 map=0.04697


=== hybrid_lambdamart_blend0.4 ===
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/bin/python -m src.run_hybrid_two_stage --split-type per_user --split val --evaluator offline --ks 10,20 --k 10 --mode all --content-n-neighbors 5 --cf-candidates 400 --cb-candidates 120 --train-cf-candidates 200 --train-cb-candidates 60 --rerank-holdout-frac 0.10 --seed 42 --ranker-cf-blend 0.4
2026-02-27 23:28:05,924 INFO __main__: Reranker holdout generated from training window: base_train=672936 rerank_labels=74973
2026-02-27 23:28:05,924 INFO __main__: Fitting TwoStageHybridRecommender...
2026-02-27 23:28:06,203 INFO src.models.hybrid_two_stage: Fitting BPR component...
2026-02-27 23:28:24,692 INFO src.models.bpr: BPR epoch 1/20, avg loss: 0.438777
2026-02-27 23:28:41,864 INFO src.models.bpr: BPR epoch 2/20, avg loss: 0.351692
2026-02-27 23:29:16,513 INFO src.models.bpr: BPR epoch 4/20, avg loss: 0.328003
2026-02-27 23:29:50,560 INFO src.models.bpr: BPR epoch 6/20, avg loss: 0.320536
2026-02-27 23:30:26,421 INFO src.models.bpr: BPR epoch 8/20, avg loss: 0.313990
2026-02-27 23:31:00,262 INFO src.models.bpr: BPR epoch 10/20, avg loss: 0.307143
2026-02-27 23:31:35,404 INFO src.models.bpr: BPR epoch 12/20, avg loss: 0.300973
2026-02-27 23:32:09,504 INFO src.models.bpr: BPR epoch 14/20, avg loss: 0.294364
2026-02-27 23:32:44,342 INFO src.models.bpr: BPR epoch 16/20, avg loss: 0.285633
2026-02-27 23:33:19,541 INFO src.models.bpr: BPR epoch 18/20, avg loss: 0.276491
2026-02-27 23:33:53,809 INFO src.models.bpr: BPR epoch 20/20, avg loss: 0.267014
2026-02-27 23:33:53,815 INFO src.models.hybrid_two_stage: Fitting content-based component...
2026-02-27 23:34:03,497 INFO src.models.hybrid_two_stage: Training hybrid reranker...
2026-02-27 23:34:25,253 INFO src.models.hybrid_two_stage: Reranker trained: n_users=5436 n_samples=1327761 n_features=16 positive_rate=0.0209
2026-02-27 23:34:25,253 INFO src.models.hybrid_two_stage: Reranker feature importances: {'cf_score_norm': np.int32(674), 'cf_rank_inv': np.int32(717), 'cf_rank_frac': np.int32(293), 'bpr_item_bias': np.int32(987), 'cb_score_norm': np.int32(586), 'cb_rank_inv': np.int32(352), 'cb_rank_frac': np.int32(184), 'in_cf': np.int32(1), 'in_cb': np.int32(1), 'cf_cb_interaction': np.int32(605), 'movie_mean_rating': np.int32(1000), 'log_movie_rating_count': np.int32(761), 'user_mean_rating': np.int32(1072), 'user_rating_count': np.int32(982), 'user_liked_count': np.int32(785), 'is_cold_user': np.int32(0)}
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(
2026-02-27 23:34:53,947 WARNING src.eval.offline_ranking: Skipped 41/6040 users with no relevant items in test set (threshold=4.00)
2026-02-27 23:34:53,977 INFO __main__: === Offline Evaluation ===
2026-02-27 23:34:53,978 INFO __main__: Split type: per_user
2026-02-27 23:34:53,978 INFO __main__: Split: val
2026-02-27 23:34:53,978 INFO __main__: Mode: all
2026-02-27 23:34:53,978 INFO __main__: Users total=6040, with_gt=6040, eligible=5999, evaluated=5999, skipped=41
2026-02-27 23:34:53,978 INFO __main__: Coverage rate=1.00000, avg list size=20.00, skip rate=0.00679
2026-02-27 23:34:53,978 INFO __main__: k=10: ndcg=0.12698 precision=0.10900 recall=0.05034 mrr=0.23632 map=0.05730
2026-02-27 23:34:53,978 INFO __main__: k=20: ndcg=0.13067 precision=0.09964 recall=0.06803 mrr=0.24620 map=0.04848

,name,note,success,ndcg_at_10,precision_at_10,recall_at_10,mrr_at_10,map_at_10,n_users_evaluated,skip_rate,elapsed_seconds
0,hybrid_no_ranker_rrf085,"Ablation: CF-dominant RRF, no ML reranker",True,0.14293,0.12292,0.05751,0.26528,0.06885,5999,0.00679,424.408643
4,hybrid_lambdamart_blend0.4,40% LambdaMART + 60% BPR CF — extends blend sweep,True,0.12698,0.10900,0.05034,0.23632,0.05730,5999,0.00679,415.366992
3,hybrid_lambdamart_blend0.6,60% LambdaMART + 40% BPR CF — best known on test,True,0.12510,0.10774,0.05010,0.23049,0.05490,5999,0.00679,414.528635
2,hybrid_lambdamart_blend0.8,80% LambdaMART + 20% BPR CF,True,0.11981,0.10291,0.04894,0.21283,0.04905,5999,0.00679,416.905259
1,hybrid_lambdamart_blend1.0,Pure LambdaMART output; no BPR score pull,True,0.10534,0.08841,0.04392,0.18787,0.03934,5999,0.00679,410.590082

In [8]:

# run the best-known config (blend=0.6) explicitly on per-user split
_BEST_CFG = next(cfg for cfg in global_variants if cfg["name"] == "hybrid_lambdamart_blend0.6")
best_per_user = run_hybrid(
    name="hybrid_lambdamart_blend0.6_per_user",
    split_type="per_user",
    split="val",
    evaluator="offline",
    extra_args=_BEST_CFG["extra_args"],
    strict=False,
)
pd.DataFrame([{**best_per_user.__dict__, "note": _BEST_CFG["note"]}])[
    ["name", "note", "success", "split_type", "split",
     "ndcg_at_10", "precision_at_10", "recall_at_10", "mrr_at_10",
     "map_at_10", "n_users_evaluated", "skip_rate", "elapsed_seconds"]
]

=== hybrid_lambdamart_blend0.6_per_user ===
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/bin/python -m src.run_hybrid_two_stage --split-type per_user --split val --evaluator offline --ks 10,20 --k 10 --mode all --content-n-neighbors 5 --cf-candidates 400 --cb-candidates 120 --train-cf-candidates 200 --train-cb-candidates 60 --rerank-holdout-frac 0.10 --seed 42 --ranker-cf-blend 0.6
2026-02-27 23:35:01,665 INFO __main__: Reranker holdout generated from training window: base_train=672936 rerank_labels=74973
2026-02-27 23:35:01,666 INFO __main__: Fitting TwoStageHybridRecommender...
2026-02-27 23:35:01,949 INFO src.models.hybrid_two_stage: Fitting BPR component...
2026-02-27 23:35:22,037 INFO src.models.bpr: BPR epoch 1/20, avg loss: 0.438777
2026-02-27 23:35:38,408 INFO src.models.bpr: BPR epoch 2/20, avg loss: 0.351692
2026-02-27 23:36:10,899 INFO src.models.bpr: BPR epoch 4/20, avg loss: 0.328003
2026-02-27 23:36:44,543 INFO src.models.bpr: BPR epoch 6/20, avg loss: 0.320536
2026-02-27 23:37:18,928 INFO src.models.bpr: BPR epoch 8/20, avg loss: 0.313990
2026-02-27 23:37:52,268 INFO src.models.bpr: BPR epoch 10/20, avg loss: 0.307143
2026-02-27 23:38:26,940 INFO src.models.bpr: BPR epoch 12/20, avg loss: 0.300973
2026-02-27 23:38:59,459 INFO src.models.bpr: BPR epoch 14/20, avg loss: 0.294364
2026-02-27 23:39:32,915 INFO src.models.bpr: BPR epoch 16/20, avg loss: 0.285633
2026-02-27 23:40:06,432 INFO src.models.bpr: BPR epoch 18/20, avg loss: 0.276491
2026-02-27 23:40:40,258 INFO src.models.bpr: BPR epoch 20/20, avg loss: 0.267014
2026-02-27 23:40:40,260 INFO src.models.hybrid_two_stage: Fitting content-based component...
2026-02-27 23:40:50,091 INFO src.models.hybrid_two_stage: Training hybrid reranker...
2026-02-27 23:41:09,919 INFO src.models.hybrid_two_stage: Reranker trained: n_users=5430 n_samples=1326153 n_features=16 positive_rate=0.0209
2026-02-27 23:41:09,923 INFO src.models.hybrid_two_stage: Reranker feature importances: {'cf_score_norm': np.int32(708), 'cf_rank_inv': np.int32(765), 'cf_rank_frac': np.int32(266), 'bpr_item_bias': np.int32(997), 'cb_score_norm': np.int32(617), 'cb_rank_inv': np.int32(349), 'cb_rank_frac': np.int32(178), 'in_cf': np.int32(1), 'in_cb': np.int32(0), 'cf_cb_interaction': np.int32(635), 'movie_mean_rating': np.int32(982), 'log_movie_rating_count': np.int32(785), 'user_mean_rating': np.int32(1031), 'user_rating_count': np.int32(924), 'user_liked_count': np.int32(762), 'is_cold_user': np.int32(0)}
/Users/anastasiiamazur/Projects/ucu-rs-2026/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRanker was fitted with feature names
  warnings.warn(
2026-02-27 23:41:38,211 WARNING src.eval.offline_ranking: Skipped 41/6040 users with no relevant items in test set (threshold=4.00)
2026-02-27 23:41:38,241 INFO __main__: === Offline Evaluation ===
2026-02-27 23:41:38,241 INFO __main__: Split type: per_user
2026-02-27 23:41:38,241 INFO __main__: Split: val
2026-02-27 23:41:38,241 INFO __main__: Mode: all
2026-02-27 23:41:38,241 INFO __main__: Users total=6040, with_gt=6040, eligible=5999, evaluated=5999, skipped=41
2026-02-27 23:41:38,241 INFO __main__: Coverage rate=1.00000, avg list size=20.00, skip rate=0.00679
2026-02-27 23:41:38,241 INFO __main__: k=10: ndcg=0.12576 precision=0.10791 recall=0.04998 mrr=0.22880 map=0.05514
2026-02-27 23:41:38,241 INFO __main__: k=20: ndcg=0.13045 precision=0.09916 recall=0.06789 mrr=0.23884 map=0.04710

,name,note,success,split_type,split,ndcg_at_10,precision_at_10,recall_at_10,mrr_at_10,map_at_10,n_users_evaluated,skip_rate,elapsed_seconds
0,hybrid_lambdamart_blend0.6_per_user,60% LambdaMART + 40% BPR CF — best known on test,True,per_user,val,0.12576,0.10791,0.04998,0.2288,0.05514,5999,0.00679,404.082423

## 5. Global vs Per-User Comparison

In [9]:

global_ok_df  = global_val_df[(global_val_df["success"]) & (global_val_df["ndcg_at_10"].notna())]
per_user_ok_df = per_user_df[(per_user_df["success"]) & (per_user_df["ndcg_at_10"].notna())]

if global_ok_df.empty or per_user_ok_df.empty:
    raise RuntimeError("Cannot build comparison: at least one protocol has no successful run.")

best_global_val  = global_ok_df.sort_values("ndcg_at_10", ascending=False).iloc[0]
best_per_user_val = per_user_ok_df.sort_values("ndcg_at_10", ascending=False).iloc[0]

_cols = ["ndcg_at_10", "precision_at_10", "recall_at_10", "mrr_at_10",
         "map_at_10", "n_users_evaluated", "skip_rate"]

rows = [
    {"protocol": "global_temporal_val",  "variant": best_global_val["name"],
     **{c: best_global_val[c]  for c in _cols}},
    {"protocol": "global_temporal_test", "variant": best_global_test.name,
     **{"ndcg_at_10": best_global_test.ndcg_at_10,
        "precision_at_10": best_global_test.precision_at_10,
        "recall_at_10": best_global_test.recall_at_10,
        "mrr_at_10": best_global_test.mrr_at_10,
        "map_at_10": best_global_test.map_at_10,
        "n_users_evaluated": best_global_test.n_users_evaluated,
        "skip_rate": best_global_test.skip_rate}},
    {"protocol": "per_user_temporal_val", "variant": best_per_user_val["name"],
     **{c: best_per_user_val[c] for c in _cols}},
]

protocol_compare = pd.DataFrame(rows)
protocol_compare

,protocol,variant,ndcg_at_10,precision_at_10,recall_at_10,mrr_at_10,map_at_10,n_users_evaluated,skip_rate
0,global_temporal_val,hybrid_no_ranker_rrf085,0.29570,0.26396,0.05564,0.46636,0.17936,1188,0.80331
1,global_temporal_test,hybrid_no_ranker_rrf085_test,0.23709,0.21007,0.04958,0.37669,0.13406,1347,0.77699
2,per_user_temporal_val,hybrid_no_ranker_rrf085,0.14293,0.12292,0.05751,0.26528,0.06885,5999,0.00679

In [10]:
global_val_df.to_csv("global_val_runs.csv", index=False)
per_user_df.to_csv("per_user_val_runs.csv", index=False)
protocol_compare.to_csv("protocol_compare.csv", index=False)